sudo: false
language: ruby
cache: bundler
rvm: 2.2.2
before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "psql -c 'create database cobot_slack_test;' -U postgres"
  - "bundle exec rake db:migrate"
script: "bundle exec rake"
services: postgresql
